# Generated by Django 4.2.4 on 2023-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='knife',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='knife',
            name='type',
            field=models.CharField(max_length=300),
        ),
    ]
