# Generated by Django 4.2.4 on 2023-08-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sharpening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharpening',
            old_name='status',
            new_name='condition',
        ),
        migrations.AlterField(
            model_name='sharpening',
            name='date',
            field=models.DateField(verbose_name='Sharpening Date'),
        ),
    ]
