# Generated by Django 4.2.4 on 2023-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_status_sharpening_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='knife',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
