# Generated by Django 4.2.4 on 2023-08-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_accessories_knife_accessory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knife',
            old_name='accessory',
            new_name='accessories',
        ),
    ]
